# Generated by Django 4.2.30 on 2026-07-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_cachedcontent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cachedcontent',
            name='books_cached_status_req_idx',
        ),
        migrations.AlterField(
            model_name='book',
            name='download_count',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
